name: Build Executable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install nuitka
    - run: python -m nuitka --standalone --onefile --windows-disable-console --include-data-dir=.=. --assume-yes-for-downloads main.py
    - run: |
        choco install upx -y
        upx --best --lzma main.exe
    - uses: actions/upload-artifact@v4
      with:
        name: main.exe
        path: main.exe
