name: Build Executable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller --name=YourAppName --windowed --onefile main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YourAppName
        path: dist/YourAppName.exe
