name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        # If you have additional dependencies, uncomment the next line:
        # pip install -r requirements.txt
    - name: Build executable
      run: |
        python -m nuitka --standalone --onefile --windows-disable-console main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: main.exe
