food_data = [
{"id": "1", "names": {"en": "Water", "nl": "Water", "es": "Agua", "fr": "Eau", "de": "Wasser", "it": "Acqua", "pt": "Água", "ja": "水", "zh": "水", "ar": "ماء"}, "measurements": {"cup": "240", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "2", "names": {"en": "Flour", "nl": "Meel", "es": "Harina", "fr": "Farine", "de": "Mehl", "it": "Farina", "pt": "Farinha", "ja": "小麦粉", "zh": "面粉", "ar": "دقيق"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454", "teaspoon": "3", "tablespoon": "9"}},
{"id": "3", "names": {"en": "Sugar", "nl": "Suiker", "es": "Azúcar", "fr": "Sucre", "de": "Zucker", "it": "Zucchero", "pt": "Açúcar", "ja": "砂糖", "zh": "糖", "ar": "سكر"}, "measurements": {"cup": "200", "ounce": "28", "pound": "454", "teaspoon": "4", "tablespoon": "12"}},
{"id": "4", "names": {"en": "Oil", "nl": "Olie", "es": "Aceite", "fr": "Huile", "de": "Öl", "it": "Olio", "pt": "Óleo", "ja": "油", "zh": "油", "ar": "زيت"}, "measurements": {"cup": "218", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "5", "names": {"en": "Salt", "nl": "Zout", "es": "Sal", "fr": "Sel", "de": "Salz", "it": "Sale", "pt": "Sal", "ja": "塩", "zh": "盐", "ar": "ملح"}, "measurements": {"cup": "273", "ounce": "28", "pound": "454", "teaspoon": "6", "tablespoon": "18"}},
{"id": "6", "names": {"en": "Cream", "nl": "Room", "es": "Crema", "fr": "Crème", "de": "Sahne", "it": "Panna", "pt": "Nata", "ja": "クリーム", "zh": "奶油", "ar": "كريمة"}, "measurements": {"cup": "240", "ounce": "28", "pound": "454"}},
{"id": "7", "names": {"en": "Rice", "nl": "Rijst", "es": "Arroz", "fr": "Riz", "de": "Reis", "it": "Riso", "pt": "Arroz", "ja": "米", "zh": "米", "ar": "أرز"}, "measurements": {"cup": "185", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "8", "names": {"en": "Cheese (grated)", "nl": "Kaas (geraspt)", "es": "Queso (rallado)", "fr": "Fromage (râpé)", "de": "Käse (gerieben)", "it": "Formaggio (grattugiato)", "pt": "Queijo (ralado)", "ja": "チーズ（おろし）", "zh": "奶酪（磨碎的）", "ar": "جبن (مبشور)"}, "measurements": {"cup": "100", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "9", "names": {"en": "Chopped Onions", "nl": "Gesnipperde Uien", "es": "Cebollas Picadas", "fr": "Oignons Hachés", "de": "Gehackte Zwiebeln", "it": "Cipolle Tritate", "pt": "Cebolas Picadas", "ja": "刻んだ玉ねぎ", "zh": "切碎的洋葱", "ar": "بصل مفروم"}, "measurements": {"cup": "150", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "10", "names": {"en": "Potato", "nl": "Aardappel", "es": "Papa", "fr": "Pomme de terre", "de": "Kartoffel", "it": "Patata", "pt": "Batata", "ja": "じゃがいも", "zh": "土豆", "ar": "بطاطس"}, "measurements": {"pound": "454"}},
{"id": "11", "names": {"en": "Pasta", "nl": "Pasta", "es": "Pasta", "fr": "Pâtes", "de": "Pasta", "it": "Pasta", "pt": "Massa", "ja": "パスタ", "zh": "意大利面", "ar": "مكرونة"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "12", "names": {"en": "Yogurt", "nl": "Yoghurt", "es": "Yogur", "fr": "Yaourt", "de": "Joghurt", "it": "Yogurt", "pt": "Iogurte", "ja": "ヨーグルト", "zh": "酸奶", "ar": "زبادي"}, "measurements": {"cup": "245", "ounce": "28", "pound": "454"}},
{"id": "13", "names": {"en": "Meat", "nl": "Vlees", "es": "Carne", "fr": "Viande", "de": "Fleisch", "it": "Carne", "pt": "Carne", "ja": "肉", "zh": "肉", "ar": "لحم"}, "measurements": {"ounce": "28", "pound": "454"}},
{"id": "14", "names": {"en": "Fish", "nl": "Vis", "es": "Pescado", "fr": "Poisson", "de": "Fisch", "it": "Pesce", "pt": "Peixe", "ja": "魚", "zh": "鱼", "ar": "سمك"}, "measurements": {"ounce": "28", "pound": "454"}},
{"id": "15", "names": {"en": "Tofu", "nl": "Tofu", "es": "Tofu", "fr": "Tofu", "de": "Tofu", "it": "Tofu", "pt": "Tofu", "ja": "豆腐", "zh": "豆腐", "ar": "توفو"}, "measurements": {"cup": "126", "ounce": "28", "pound": "454"}},
{"id": "16", "names": {"en": "Leafy Greens", "nl": "Groene Bladeren", "es": "Verduras de Hoja", "fr": "Légumes Feuillus", "de": "Blattgemüse", "it": "Verdure a Foglia", "pt": "Verduras Folhosas", "ja": "葉物野菜", "zh": "绿叶蔬菜", "ar": "الخضروات الورقية"}, "measurements": {"cup": "30", "ounce": "28", "pound": "454"}},
{"id": "17", "names": {"en": "Non-Leafy Vegetables", "nl": "Niet-Bladgroenten", "es": "Verduras No Foliares", "fr": "Légumes Non Feuillus", "de": "Nicht-Blattgemüse", "it": "Verdure Non a Foglia", "pt": "Vegetais Não Folhosos", "ja": "非葉野菜", "zh": "非叶类蔬菜", "ar": "الخضروات غير الورقية"}, "measurements": {"cup": "150", "ounce": "28", "pound": "454"}},
{"id": "18", "names": {"en": "Chopped Garlic", "nl": "Fijngehakte Knoflook", "es": "Ajo Picado", "fr": "Ail Haché", "de": "Gehackter Knoblauch", "it": "Aglio Tritato", "pt": "Alho Picado", "ja": "刻んだニンニク", "zh": "切碎的大蒜", "ar": "ثوم مفروم"}, "measurements": {"ounce": "28", "teaspoon": "3", "tablespoon": "9"}},
{"id": "19", "names": {"en": "Butter", "nl": "Boter", "es": "Mantequilla", "fr": "Beurre", "de": "Butter", "it": "Burro", "pt": "Manteiga", "ja": "バター", "zh": "黄油", "ar": "زبدة"}, "measurements": {"cup": "227", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "20", "names": {"en": "Baking powder", "nl": "Bakpoeder", "es": "Polvo de hornear", "fr": "Levure chimique", "de": "Backpulver", "it": "Lievito in polvere", "pt": "Fermento em pó", "ja": "ベーキングパウダー", "zh": "发酵粉", "ar": "خميرة كيميائية"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454", "teaspoon": "3", "tablespoon": "9"}},
{"id": "21", "names": {"en": "Cornstarch", "nl": "Maïzena", "es": "Maicena", "fr": "Fécule de maïs", "de": "Maisstärke", "it": "Amido di mais", "pt": "Amido de milho", "ja": "コーンスターチ", "zh": "玉米淀粉", "ar": "نشا الذرة"}, "measurements": {"cup": "128", "ounce": "28", "pound": "454", "teaspoon": "3", "tablespoon": "9"}},
{"id": "22", "names": {"en": "Honey", "nl": "Honing", "es": "Miel", "fr": "Miel", "de": "Honig", "it": "Miele", "pt": "Mel", "ja": "蜂蜜", "zh": "蜂蜜", "ar": "عسل"}, "measurements": {"cup": "340", "ounce": "28", "pound": "454", "teaspoon": "7", "tablespoon": "21"}},
{"id": "23", "names": {"en": "Couscous", "nl": "Couscous", "es": "Cuscús", "fr": "Couscous", "de": "Couscous", "it": "Cuscus", "pt": "Cuscuz", "ja": "クスクス", "zh": "库斯库斯", "ar": "كسكسي"}, "measurements": {"cup": "180", "ounce": "28", "pound": "454", "teaspoon": "10", "tablespoon": "30"}},
{"id": "24", "names": {"en": "Icing sugar", "nl": "Poedersuiker", "es": "Azúcar glas", "fr": "Sucre glace", "de": "Puderzucker", "it": "Zucchero a velo", "pt": "Açúcar de confeiteiro", "ja": "粉砂糖", "zh": "糖粉", "ar": "سكر بودرة"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454", "teaspoon": "3", "tablespoon": "9"}},
{"id": "25", "names": {"en": "Bread crumbs", "nl": "Paneermeel", "es": "Pan rallado", "fr": "Chapelure", "de": "Semmelbrösel", "it": "Pangrattato", "pt": "Farinha de rosca", "ja": "パン粉", "zh": "面包屑", "ar": "فتات الخبز"}, "measurements": {"cup": "60", "ounce": "28", "pound": "454", "teaspoon": "1", "tablespoon": "3"}},
{"id": "26", "names": {"en": "Rice flour", "nl": "Rijstmeel", "es": "Harina de arroz", "fr": "Farine de riz", "de": "Reismehl", "it": "Farina di riso", "pt": "Farinha de arroz", "ja": "米粉", "zh": "米粉", "ar": "دقيق الأرز"}, "measurements": {"cup": "158", "ounce": "28", "pound": "454", "teaspoon": "4", "tablespoon": "12"}},
{"id": "27", "names": {"en": "Lentils", "nl": "Linzen", "es": "Lentejas", "fr": "Lentilles", "de": "Linsen", "it": "Lenticchie", "pt": "Lentilhas", "ja": "レンズ豆", "zh": "扁豆", "ar": "عدس"}, "measurements": {"cup": "200", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "28", "names": {"en": "Split peas", "nl": "Spliterwten", "es": "Guisantes partidos", "fr": "Pois cassés", "de": "Gesplittete Erbsen", "it": "Piselli spezzati", "pt": "Ervilhas partidas", "ja": "スプリットピース", "zh": "干豌豆", "ar": "البازلاء المجففة"}, "measurements": {"cup": "200", "ounce": "28", "pound": "454", "teaspoon": "5", "tablespoon": "15"}},
{"id": "29", "names": {"en": "Chickpeas", "nl": "Kikkererwten", "es": "Garbanzos", "fr": "Pois chiches", "de": "Kichererbsen", "it": "Ceci", "pt": "Grão-de-bico", "ja": "ひよこ豆", "zh": "鹰嘴豆", "ar": "حمص"}, "measurements": {"cup": "200", "ounce": "28", "pound": "454", "teaspoon": "6", "tablespoon": "18"}},
{"id": "30", "names": {"en": "Black beans", "nl": "Zwarte bonen", "es": "Frijoles negros", "fr": "Haricots noirs", "de": "Schwarze Bohnen", "it": "Fagioli neri", "pt": "Feijão preto", "ja": "黒豆", "zh": "黑豆", "ar": "فاصوليا سوداء"}, "measurements": {"cup": "240", "ounce": "28", "pound": "454", "teaspoon": "6", "tablespoon": "18"}},
{"id": "31", "names": {"en": "Tomato (chopped canned)", "nl": "Tomaten (gesneden, uit blik)", "es": "Tomate (picada enlatada)", "fr": "Tomate (hachée en conserve)", "de": "Tomaten (gehackt aus der Dose)", "it": "Pomodoro (tritato in scatola)", "pt": "Tomate (picado enlatado)", "ja": "トマト（刻み缶詰）", "zh": "番茄（罐装切碎）", "ar": "طماطم (معلبة مقطعة)"}, "measurements": {"cup": "240", "ounce": "28", "pound": "454", "teaspoon": "6", "tablespoon": "18"}},
{"id": "32", "names": {"en": "Tomato paste", "nl": "Tomatenpuree", "es": "Pasta de tomate", "fr": "Concentré de tomate", "de": "Tomatenmark", "it": "Concentrato di pomodoro", "pt": "Extrato de tomate", "ja": "トマトペースト", "zh": "番茄酱", "ar": "معجون الطماطم"}, "measurements": {"cup": "260", "ounce": "28", "pound": "454", "teaspoon": "6", "tablespoon": "18"}},
{"id": "33", "names": {"en": "Powdered spices", "nl": "Poedervormige specerijen", "es": "Especias en polvo", "fr": "Épices en poudre", "de": "Gemahlene Gewürze", "it": "Spezie in polvere", "pt": "Especiarias em pó", "ja": "粉末スパイス", "zh": "粉状香料", "ar": "توابل مطحونة"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454", "teaspoon": "3", "tablespoon": "9"}},
{"id": "34", "names": {"en": "Cumin seeds", "nl": "Komijnzaad", "es": "Semillas de comino", "fr": "Graines de cumin", "de": "Kreuzkümmelsamen", "it": "Semi di cumino", "pt": "Sementes de cominho", "ja": "クミンシード", "zh": "孜然", "ar": "بذور الكمون"}, "measurements": {"cup": "130", "ounce": "28", "pound": "454"}},
{"id": "35", "names": {"en": "Coriander seeds", "nl": "Korianderzaad", "es": "Semillas de cilantro", "fr": "Graines de coriandre", "de": "Koriandersamen", "it": "Semi di coriandolo", "pt": "Sementes de coentro", "ja": "コリアンダーシード", "zh": "芫荽籽", "ar": "بذور الكزبرة"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "36", "names": {"en": "Mustard seeds", "nl": "Mosterdzaad", "es": "Semillas de mostaza", "fr": "Graines de moutarde", "de": "Senfsamen", "it": "Semi di senape", "pt": "Sementes de mostarda", "ja": "マスタードシード", "zh": "芥菜籽", "ar": "بذور الخردل"}, "measurements": {"cup": "140", "ounce": "28", "pound": "454"}},
{"id": "37", "names": {"en": "Fennel seeds", "nl": "Venkelzaad", "es": "Semillas de hinojo", "fr": "Graines de fenouil", "de": "Fenchelsamen", "it": "Semi di finocchio", "pt": "Sementes de funcho", "ja": "フェンネルシード", "zh": "茴香种子", "ar": "بذور الشمر"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "38", "names": {"en": "Pumpkin seeds", "nl": "Pompoenpitten", "es": "Semillas de calabaza", "fr": "Graines de courge", "de": "Kürbiskerne", "it": "Semi di zucca", "pt": "Sementes de abóbora", "ja": "かぼちゃの種", "zh": "南瓜种子", "ar": "بذور اليقطين"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "39", "names": {"en": "Sesame seeds", "nl": "Sesamzaad", "es": "Semillas de sésamo", "fr": "Graines de sésame", "de": "Sesamsamen", "it": "Semi di sesamo", "pt": "Sementes de sésamo", "ja": "ゴマの種", "zh": "芝麻种子", "ar": "بذور السمسم"}, "measurements": {"cup": "144", "ounce": "28", "pound": "454"}},
{"id": "40", "names": {"en": "Sunflower seeds", "nl": "Zonnebloemzaad", "es": "Semillas de girasol", "fr": "Graines de tournesol", "de": "Sonnenblumenkerne", "it": "Semi di girasole", "pt": "Sementes de girassol", "ja": "ひまわりの種", "zh": "向日葵种子", "ar": "بذور عباد الشمس"}, "measurements": {"cup": "130", "ounce": "28", "pound": "454"}},
{"id": "41", "names": {"en": "Cashews", "nl": "Cashewnoten", "es": "Anacardos", "fr": "Noix de cajou", "de": "Cashewnüsse", "it": "Anacardi", "pt": "Castanhas de caju", "ja": "カシューナッツ", "zh": "腰果", "ar": "كاجو"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "42", "names": {"en": "Almonds", "nl": "Amandelen", "es": "Almendras", "fr": "Amandes", "de": "Mandeln", "it": "Mandorle", "pt": "Amêndoas", "ja": "アーモンド", "zh": "杏仁", "ar": "لوز"}, "measurements": {"cup": "140", "ounce": "28", "pound": "454"}},
{"id": "43", "names": {"en": "Hazelnuts", "nl": "Hazelnoten", "es": "Avellanas", "fr": "Noisettes", "de": "Haselnüsse", "it": "Nocciole", "pt": "Avelãs", "ja": "ヘーゼルナッツ", "zh": "榛子", "ar": "بندق"}, "measurements": {"cup": "130", "ounce": "28", "pound": "454"}},
{"id": "44", "names": {"en": "Walnuts", "nl": "Walnoten", "es": "Nueces", "fr": "Noix", "de": "Walnüsse", "it": "Noci", "pt": "Nozes", "ja": "クルミ", "zh": "核桃", "ar": "جوز"}, "measurements": {"cup": "100", "ounce": "28", "pound": "454"}},
{"id": "45", "names": {"en": "Pistachios", "nl": "Pistachenoten", "es": "Pistachos", "fr": "Pistaches", "de": "Pistazien", "it": "Pistacchi", "pt": "Pistácios", "ja": "ピスタチオ", "zh": "开心果", "ar": "فستق حلبي"}, "measurements": {"cup": "120", "ounce": "28", "pound": "454"}},
{"id": "46", "names": {"en": "Raisins", "nl": "Rozijnen", "es": "Pasas", "fr": "Raisins secs", "de": "Rosinen", "it": "Uvetta", "pt": "Passas", "ja": "レーズン", "zh": "葡萄干", "ar": "زبيب"}, "measurements": {"cup": "170", "ounce": "28", "pound": "454"}},
{"id": "47", "names": {"en": "Apricots", "nl": "Abrikozen", "es": "Albaricoques", "fr": "Abricots", "de": "Aprikosen", "it": "Albicocche", "pt": "Damascos", "ja": "アプリコット", "zh": "杏", "ar": "مشمش"}, "measurements": {"cup": "130", "ounce": "28", "pound": "454"}}
]     



buttonstext = {
    "en": {
        "button_convert": "Convert",
        "button_copy": "Copy",
        "button_reset": "Reset",
        "button_multiply_divide": "Multiply Results With (e.g. 2 or 0.5) :",
        "lang_select_col1": "Main Language",
        "lang_select_col2": "0-3 translation languages",
        "button_recipes": "Load Saved Recipe",
        "button_save_recipe": "Save Recipe",
        "choose_name": "Choose Name",
        "load": "Load",
        "rename": "Rename",
        "delete": "Delete",
        "are_you_sure": "Are you sure?",
        "overwrite_recipe": "Overwrite recipe?",
        "yes": "Yes",
        "no": "No",
        "button_back": "Back"
    },
    "nl": {
        "button_convert": "Converteren",
        "button_copy": "Kopiëren",
        "button_reset": "Resetten",
        "button_multiply_divide": "Resultaten Vermenigvuldigen Met (bijv. 2 of 0,5) :",
        "lang_select_col1": "Hoofdtaal",
        "lang_select_col2": "0-3 vertaaltalen",
        "button_recipes": "Opgeslagen Recept Laden",
        "button_save_recipe": "Recept Opslaan",
        "choose_name": "Kies Naam",
        "load": "Laden",
        "rename": "Hernoemen",
        "delete": "Verwijderen",
        "are_you_sure": "Weet je het zeker?",
        "overwrite_recipe": "Recept overschrijven?",
        "yes": "Ja",
        "no": "Nee",
        "button_back": "Terug"
    },
    "es": {
        "button_convert": "Convertir",
        "button_copy": "Copiar",
        "button_reset": "Restablecer",
        "button_multiply_divide": "Multiplicar Resultados Con (ej. 2 o 0,5) :",
        "lang_select_col1": "Idioma principal",
        "lang_select_col2": "0-3 idiomas de traducción",
        "button_recipes": "Cargar Receta Guardada",
        "button_save_recipe": "Guardar Receta",
        "choose_name": "Elegir Nombre",
        "load": "Cargar",
        "rename": "Renombrar",
        "delete": "Eliminar",
        "are_you_sure": "¿Estás seguro?",
        "overwrite_recipe": "¿Sobrescribir receta?",
        "yes": "Sí",
        "no": "No",
        "button_back": "Atrás"
    },
    "fr": {
        "button_convert": "Convertir",
        "button_copy": "Copier",
        "button_reset": "Réinitialiser",
        "button_multiply_divide": "Multiplier les Résultats Avec (ex. 2 ou 0,5) :",
        "lang_select_col1": "Langue principale",
        "lang_select_col2": "0-3 langues de traduction",
        "button_recipes": "Charger une Recette Sauvegardée",
        "button_save_recipe": "Sauvegarder la Recette",
        "choose_name": "Choisir un Nom",
        "load": "Charger",
        "rename": "Renommer",
        "delete": "Supprimer",
        "are_you_sure": "Êtes-vous sûr ?",
        "overwrite_recipe": "Écraser la recette ?",
        "yes": "Oui",
        "no": "Non",
        "button_back": "Retour"
    },
    "de": {
        "button_convert": "Konvertieren",
        "button_copy": "Kopieren",
        "button_reset": "Zurücksetzen",
        "button_multiply_divide": "Ergebnisse Multiplizieren Mit (z.B. 2 oder 0,5) :",
        "lang_select_col1": "Hauptsprache",
        "lang_select_col2": "0-3 Übersetzungssprachen",
        "button_recipes": "Gespeichertes Rezept Laden",
        "button_save_recipe": "Rezept Speichern",
        "choose_name": "Namen Wählen",
        "load": "Laden",
        "rename": "Umbenennen",
        "delete": "Löschen",
        "are_you_sure": "Sind Sie sicher?",
        "overwrite_recipe": "Rezept überschreiben?",
        "yes": "Ja",
        "no": "Nein",
        "button_back": "Zurück"
    },
    "it": {
        "button_convert": "Convertire",
        "button_copy": "Copiare",
        "button_reset": "Reimpostare",
        "button_multiply_divide": "Moltiplicare i Risultati Con (es. 2 o 0,5) :",
        "lang_select_col1": "Lingua principale",
        "lang_select_col2": "0-3 lingue di traduzione",
        "button_recipes": "Carica Ricetta Salvata",
        "button_save_recipe": "Salva Ricetta",
        "choose_name": "Scegli Nome",
        "load": "Carica",
        "rename": "Rinomina",
        "delete": "Elimina",
        "are_you_sure": "Sei sicuro?",
        "overwrite_recipe": "Sovrascrivere la ricetta?",
        "yes": "Sì",
        "no": "No",
        "button_back": "Indietro"
    },
    "pt": {
        "button_convert": "Converter",
        "button_copy": "Copiar",
        "button_reset": "Redefinir",
        "button_multiply_divide": "Multiplicar Resultados Com (ex. 2 ou 0,5) :",
        "lang_select_col1": "Idioma principal",
        "lang_select_col2": "0-3 idiomas de tradução",
        "button_recipes": "Carregar Receita Salva",
        "button_save_recipe": "Salvar Receita",
        "choose_name": "Escolher Nome",
        "load": "Carregar",
        "rename": "Renomear",
        "delete": "Excluir",
        "are_you_sure": "Tem certeza?",
        "overwrite_recipe": "Substituir receita?",
        "yes": "Sim",
        "no": "Não",
        "button_back": "Voltar"
    },
    "ja": {
        "button_convert": "変換する",
        "button_copy": "コピー",
        "button_reset": "リセット",
        "button_multiply_divide": "結果を掛ける係数 (例: 2 または 0.5) :",
        "lang_select_col1": "主要言語",
        "lang_select_col2": "0～3の翻訳言語",
        "button_recipes": "保存したレシピを読み込む",
        "button_save_recipe": "レシピを保存",
        "choose_name": "名前を選択",
        "load": "読み込む",
        "rename": "名前を変更",
        "delete": "削除",
        "are_you_sure": "本当によろしいですか？",
        "overwrite_recipe": "レシピを上書きしますか？",
        "yes": "はい",
        "no": "いいえ",
        "button_back": "戻る"
    },
    "zh": {
        "button_convert": "转换",
        "button_copy": "复制",
        "button_reset": "重置",
        "button_multiply_divide": "乘以结果的系数 (例如 2 或 0.5) :",
        "lang_select_col1": "主要语言",
        "lang_select_col2": "0-3种翻译语言",
        "button_recipes": "加载已保存的食谱",
        "button_save_recipe": "保存食谱",
        "choose_name": "选择名称",
        "load": "加载",
        "rename": "重命名",
        "delete": "删除",
        "are_you_sure": "确定吗？",
        "overwrite_recipe": "覆盖食谱？",
        "yes": "是",
        "no": "否",
        "button_back": "返回"
    },
    "ar": {
        "button_convert": "تحويل",
        "button_copy": "نسخ",
        "button_reset": "إعادة تعيين",
        "button_multiply_divide": "ضرب النتائج بـ (مثل 2 أو 0.5) :",
        "lang_select_col1": "اللغة الرئيسية",
        "lang_select_col2": "0-3 لغات ترجمة",
        "button_recipes": "تحميل الوصفة المحفوظة",
        "button_save_recipe": "حفظ الوصفة",
        "choose_name": "اختر اسمًا",
        "load": "تحميل",
        "rename": "إعادة تسمية",
        "delete": "حذف",
        "are_you_sure": "هل أنت متأكد؟",
        "overwrite_recipe": "استبدال الوصفة؟",
        "yes": "نعم",
        "no": "لا",
        "button_back": "رجوع"
    }
}


unit_translations = {
    'zh': {'gram': '克', 'kilogram': '千克'},
    'ar': {'gram': 'جرام', 'kilogram': 'كيلوجرام'},
    'ja': {'gram': 'グラム', 'kilogram': 'キログラム'}
}


multiresults = {
    "en": "All Results x",
    "nl": "Alle Resultaten x",
    "es": "Todos Los Resultados x",
    "fr": "Tous Les Résultats x",
    "de": "Alle Ergebnisse x",
    "it": "Tutti I Risultati x",
    "pt": "Todos Os Resultados x",
    "ja": "すべての結果 x",
    "zh": "所有 结果 x",
    "ar": "جميع النتائج x"
}


